name: CI

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write  # ✅ Required for deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x  # ✅ Use stable LTS version
          cache: 'npm'  # ✅ Cache dependencies for faster builds
      - name: Install Dependencies
        run: npm install --legacy-peer-deps  # ✅ Ensures reproducible installs
      - name: Build
        run: npm run build
      - name: Checkout TypeScript Errors
        run: npm i -g typescript && tsc
      - name: Checkout Eslint Errors
        run: npm run eslint
      - name: Unit & Integration Tests
        run: npm run test
      
