name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.X
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Checkout TypeScript Errors
        run: npm i -g typescript && tsc
      - name: Checkout Eslint Errors
        run: npm run eslint
      - name: Unit & Integration Tests
        run: npm run test
      - name: Deploy
        uses: actions/deploy-to-github-pages@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
      
